name: SetPwsh plugin Multiplatform Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

defaults:
  run:
    shell: pwsh

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    env:
      RELEASE_VERSION: '9.1.1852'
    steps:
      - name: Workaround cairo includes on macos
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          # https://gist.github.com/Samk13/6fe053f6aea21727a8fb6ab7cb92709b
          mkdir /opt/homebrew/Cellar/cairo/1.18.4/include/cairo/cairo
          cp /opt/homebrew/Cellar/cairo/1.18.4/include/cairo/*.h /opt/homebrew/Cellar/cairo/1.18.4/include/cairo/cairo
        
      - name: Install Vim
        run: |
          $basedir = Get-Location
          "BASEDIR=$basedir" | Out-File -Path $Env:GITHUB_ENV -Encoding OEM -Append

          New-Item -Type Directory -Path workplace | pushd

          Invoke-WebRequest -Uri https://github.com/vim/vim/archive/refs/tags/v$Env:RELEASE_VERSION.zip `
                            -OutFile vim.zip

          Expand-Archive -Path vim.zip -DestinationPath . && Remove-Item vim.zip
          $bindir = (Get-Item -Path vim*/src).FullName

          "TESTDIR=$bindir/testdir" | Out-File -Path $Env:GITHUB_ENV -Encoding OEM -Append

          if ($IsWindows)
          {
            # Windows world: use precompiled binaries
            Invoke-WebRequest -OutFile gvim.zip `
                              -Uri https://github.com/vim/vim-win32-installer/releases/download/v$Env:RELEASE_VERSION/gvim_${Env:RELEASE_VERSION}_x64.zip
            Expand-Archive -Path gvim.zip -DestinationPath . && rm gvim.zip
            $vimdir = Get-Item -Path vim/vim*/vim.exe | Split-Path -Parent
            Move-Item -Path $vimdir/* -Destination $bindir -Force
          }
          else
          {
            # UNIX world: build from sources
            if ($IsMacOS)
            {
              Write-Warning "MacOS lacks GUI support. Check on https://github.com/macvim-dev/macvim"
            }
            else # Ubuntu runner
            {
              sudo apt-get install -y libx11-dev libxt-dev libxpm-dev libgtk2.0-dev libncurses-dev
            }

            gi ./vim*/src | pushd
            ./configure --prefix=/tmp/workplace --enable-gui=auto
            # Get-Content -Path ./auto/config.mk
            # Get-Content -Path ./auto/config.log
            make
            popd
          }

          # local
          $Env:PATH = "$bindir$([system.io.path]::PathSeparator)$Env:PATH"
          # persistent
          $bindir | Out-File -Path $Env:GITHUB_PATH -Encoding OEM -Append

      - name: Check vim binaries
        run: |
          # gcm vim | select Source
          vim --version

      - name: Check testing
        run: |
          cd $Env:TESTDIR

          vim -u NONE -S runtest.vim test_plugin_glvs.vim
          if (Test-Path -Path messages)
          {
            Get-Content -Path messages
            if ( Select-String -Path messages -Pattern 'FAILED' )
            {
              throw "Some tests failed!!!"
            }
            Remove-Item messages
          }

          if (vim --version | Select-String -Pattern 'with GTK. GUI|GUI/console') 
          {
            vim -g -u NONE -U NONE -S runtest.vim test_plugin_glvs.vim
            if (Test-Path -Path messages)
            {
              Get-Content -Path messages
              if ( Select-String -Path messages -Pattern 'FAILED' )
              {
                throw "Some tests failed!!!"
              }
            }
          }
          else
          {
            Write-Warning "No GUI support in this vim build. Skipping GUI tests."
          }


# vim: cuc sw=2 sts=2 et
